version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: firmable-postgres
    environment:
      POSTGRES_USER: firmable
      POSTGRES_PASSWORD: firmable_password
      POSTGRES_DB: firmable_companies
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
